version: "3.9"
services:
  db:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: demo
      MYSQL_USER: ynon
      MYSQL_PASSWORD: ynon
    volumes:
      - "./init:/docker-entrypoint-initdb.d/"

